# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKDplFC6nOkMCVon196dyNNr4bbjXoG5
"""

#Password Generator
import random
import string

#User Define function to define the length of the password

def standard_password_length (password_length, use_letters=True, use_digits=True, use_punctuation=True):
    password = []  # Empty list to store the required characters

# Ensure at least one letter, digit, special character
    if use_letters:
        password.append(random.choice(string.ascii_letters))
    if use_digits:
        password.append(random.choice(string.digits))
    if use_punctuation:
        custom_punctuation = '@#$%&'
        password.append(random.choice(custom_punctuation))

# Combine all the character options
    characters = []
    if use_letters:
        characters.extend(string.ascii_letters)
    if use_digits:
        characters.extend(string.digits)
    if use_punctuation:
        characters.extend(custom_punctuation)

# Fill the remaining characters randomly
    password.extend(random.choice(characters) for i in range(password_length))

# Shuffle the password to avoid predictable patterns
    random.shuffle(password)

# Generate the final password
    generated_password = ''.join(password)
    return generated_password

#Auto Password Generator
password_length = int(input("Define the length of your password: "))
password = standard_password_length(password_length)

print ("Your Generated password is:", password)