# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kFJm9YenaTjN9X4RpglcunSOwl73PR5D
"""
#Download the contain failes used in this projct from the below git link
# 1. https://github.com/sujithps/Dictionary/blob/master/Oxford%20English%20Dictionary.txt 
# 2. https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-1000000.txt

#Python script to check strength of a user define password

import re #Inbuild module to check regular expression

#Load a set of common dictionary word

def load_dictionary():
  with open ("/content/Oxford English Dictionary.txt") as f:
    words = set (word.strip().lower() for word in f)
  return words

#Load a set of common password word

def load_common_password():
  with open ("/content/10-million-password-list-top-1000000.txt") as f:
    words = set (word.strip().lower() for word in f)
  return words

#check password contain dictionary word or not

def check_dictionary_word(password, dictionary):
  password_lower=password.lower()
  for word in dictionary:
    if word in password_lower:
      return True
  return False

#check common password

def check_common_password(password, common_password):
  password_lower=password.lower()
  for enter_password in common_password:
    if enter_password in password_lower:
      return True
  return False

#user define function to check password
def password_checker (password, dictionary, common_password):
  Strength = 0 # It will help to determine the strength of an password

  #Check password contain 8 character or not
  if len(password)>=8:
    Strength +=1
  else:
    print ("password must contain atleast 8 character")

  #Check password contain digit or not
  if re.search("[0-9]",password):
    Strength+=1
  else:
    print("password should contain a digit")

  #Check password contain 1 lower case and 1 upper case
  if re.search("[a-z]",password) and re.search("[A-Z]",password):
    Strength+=1
  else:
    print("password should contain atleast one upper & lower case word")

  #check password contain atleast 2 special character
  special_character = re.findall ("[!@#$%^&*(),.?\":{}|<>]",password)
  if len(special_character)>=2:
    Strength+=1
  else:
    print ("password should contain atleast 2 special character")

  #check dictionary word
  if check_dictionary_word (password, dictionary):
    print("password should not contain dictionary word")
  else:
    Strength+=1

    #check common password
  if check_common_password (password, load_common_password()):
    print("password should not contain common password")
  else:
    Strength+=1

#check the strength of the password
  if Strength == 6:
    print("Strong password")
  elif Strength == 4:
    print("good password")
  elif Strength == 3:
    print ("moderate password")
  else:
    print("weak password")

#load dictionary word & common password

dictionary = load_dictionary()
common_password = load_common_password()

#user input password
user_password = input("Please enter your password: ")

#Check strength of an password
password_checker(user_password,dictionary,common_password)
